//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7312_P1_V1.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROG7312_P1_V1.Languages.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string aLogin {
            get {
                return ResourceManager.GetString("aLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string aSignup {
            get {
                return ResourceManager.GetString("aSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Events and Announcements.
        /// </summary>
        public static string btnEvents {
            get {
                return ResourceManager.GetString("btnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Issue.
        /// </summary>
        public static string btnLogIssue {
            get {
                return ResourceManager.GetString("btnLogIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string btnReportIssue {
            get {
                return ResourceManager.GetString("btnReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Report Status.
        /// </summary>
        public static string btnReportStatus {
            get {
                return ResourceManager.GetString("btnReportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string btnSignup {
            get {
                return ResourceManager.GetString("btnSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string lbCategory {
            get {
                return ResourceManager.GetString("lbCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string lbFullName {
            get {
                return ResourceManager.GetString("lbFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an Image.
        /// </summary>
        public static string lbImage {
            get {
                return ResourceManager.GetString("lbImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the issue:.
        /// </summary>
        public static string lbIssue {
            get {
                return ResourceManager.GetString("lbIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lbLocation {
            get {
                return ResourceManager.GetString("lbLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        public static string lbPhone {
            get {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        public static string lbReportAnIssue {
            get {
                return ResourceManager.GetString("lbReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string lbSignup {
            get {
                return ResourceManager.GetString("lbSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string opDefault {
            get {
                return ResourceManager.GetString("opDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Work.
        /// </summary>
        public static string opRoadWork {
            get {
                return ResourceManager.GetString("opRoadWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Maintenance.
        /// </summary>
        public static string opRobot {
            get {
                return ResourceManager.GetString("opRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Pipe.
        /// </summary>
        public static string opWater {
            get {
                return ResourceManager.GetString("opWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string txtAccount {
            get {
                return ResourceManager.GetString("txtAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string txtEnterEmail {
            get {
                return ResourceManager.GetString("txtEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full name.
        /// </summary>
        public static string txtEnterName {
            get {
                return ResourceManager.GetString("txtEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string txtEnterPassword {
            get {
                return ResourceManager.GetString("txtEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string txtEnterPhone {
            get {
                return ResourceManager.GetString("txtEnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string txtErrorEmailRegister {
            get {
                return ResourceManager.GetString("txtErrorEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string txtErrorLogin {
            get {
                return ResourceManager.GetString("txtErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a brief description of the issue....
        /// </summary>
        public static string txtIssueDescription {
            get {
                return ResourceManager.GetString("txtIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a brief description of the issue....
        /// </summary>
        public static string txtIssueDescription1 {
            get {
                return ResourceManager.GetString("txtIssueDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue report submitted successfully.
        /// </summary>
        public static string txtIssueReportSuccess {
            get {
                return ResourceManager.GetString("txtIssueReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location of the issue....
        /// </summary>
        public static string txtLocationIssue {
            get {
                return ResourceManager.GetString("txtLocationIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string txtNoAccount {
            get {
                return ResourceManager.GetString("txtNoAccount", resourceCulture);
            }
        }
    }
}
